name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Generate static html
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Generate static html
        uses: borales/actions-yarn@v4
        with:
          cmd: build
        env:
          BASE_URL: "/adwave-docs/"
      - run: mkdir ./artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./artifact
          retention-days: 360
      - name: Deploy
        uses: actions/deploy-pages@v2
